# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    conveyor_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_1_base_link_joint
      - left_arm_linkage_arm_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: left_gear_arm_3_joint
conveyor_controller:
  ros__parameters:
    joints:
      - left_pulley_shaft_motor_housing_joint
    command_interfaces:
      []
    state_interfaces:
      []